# Generated by Django 5.1.15 on 2026-09-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('gallery', 'Galereya / slayder'), ('about', 'Biz haqimizda'), ('hero', 'Hero (yuqori fon)')], db_index=True, default='gallery', max_length=20)),
                ('image', models.ImageField(upload_to='site/%Y/%m/')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Kichik son — oldinroq')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['section', 'order', '-created_at'],
            },
        ),
    ]
